### PR TITLE
clang-format

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
please wait before merging, I'm using this PR as a tests for the clang-format check in Jenkins. Currently waiting on the installation of "clang-format" package on Ubuntu 16.04 executors.

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by hernando** [comment]
Ready to merge?

**Comment by rdumusc** [comment]
yes, good to merge

**Pull request merged**
