### PR TITLE
Move from lunchbox::PersistentMap

### PR DESCRIPTION
**Pull request by eile**
Rewriting history got #1 killed

### CODE REVIEW

**Comment by rdumusc** [comment]
+1 for me (my updated Firefox won't let me click "approve")

**Comment by eile** [comment]
@tribal-tec ?

**Comment by eile** [comment]
Retest this please.

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
Build is failing, hence no approval :)

**Comment by eile** [comment]
Seriously? You can already review and approve the code, the CI will approve the build success. Can't be merged without CI anyways. Waiting for review on CI will prolong the PR process even longer.

**Pull request merged**
